# Generated by Django 3.2.6 on 2021-08-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GidroPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slag_name', models.CharField(default='', max_length=100)),
                ('index_posta', models.IntegerField(unique=True)),
                ('geografic_koord', models.CharField(max_length=200)),
                ('height_BS', models.IntegerField(unique=True)),
                ('istory_max_level', models.IntegerField()),
                ('reper', models.IntegerField(unique=True)),
                ('reyka_max_pruvodka', models.IntegerField()),
                ('pali_pruvodka', models.IntegerField()),
                ('sposterigach', models.CharField(max_length=500)),
                ('telefon', models.IntegerField()),
                ('nebezpecni_yavusha', models.IntegerField()),
                ('stuchiyni_yavusha', models.IntegerField()),
                ('lavel_pidtoplenya', models.IntegerField()),
                ('zonu_pidtoplenya', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('baseyn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('last_message', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pruladu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nomer', models.CharField(max_length=50)),
                ('avtomatic_post', models.CharField(max_length=100)),
                ('peredano', models.DateTimeField()),
                ('povireno', models.DateTimeField()),
                ('povirka_grafik', models.DateTimeField()),
                ('termin_povirku', models.IntegerField(unique=True)),
                ('stan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.gidropost')),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField()),
                ('report_type', models.IntegerField(choices=[(1, 'Manual'), (2, 'Maws'), (3, 'Aivs')], default=1)),
                ('station_name', models.CharField(max_length=200)),
                ('battery', models.DecimalField(decimal_places=3, max_digits=7)),
                ('qml_Voltage', models.DecimalField(decimal_places=3, max_digits=7)),
                ('qml_temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=7)),
                ('air_pressure', models.DecimalField(decimal_places=3, max_digits=7)),
                ('soil_temperature', models.DecimalField(decimal_places=3, max_digits=7)),
                ('water_level', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pruvodka', models.DecimalField(decimal_places=3, max_digits=7)),
                ('water_level_BS', models.DecimalField(decimal_places=3, max_digits=7)),
                ('water_level_ymov', models.DecimalField(decimal_places=3, max_digits=7)),
                ('precipitation', models.DecimalField(decimal_places=3, max_digits=7)),
                ('precipitation_1h', models.DecimalField(decimal_places=3, max_digits=7)),
                ('precipitation_doba', models.DecimalField(decimal_places=3, max_digits=7)),
                ('precipitation_den', models.DecimalField(decimal_places=3, max_digits=7)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.gidropost')),
            ],
        ),
        migrations.AddField(
            model_name='gidropost',
            name='river',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.river'),
        ),
    ]
