# Generated by Django 3.2.6 on 2021-08-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210823_2213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('post', 'report_time', 'report_type')},
        ),
    ]
