# Generated by Django 3.2.6 on 2021-08-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_postreport_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gidropost',
            old_name='name',
            new_name='name_post',
        ),
    ]
