# Generated by Django 3.2.6 on 2021-08-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_name_gidropost_name_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruladu',
            old_name='name',
            new_name='name_prulad',
        ),
        migrations.RenameField(
            model_name='river',
            old_name='name',
            new_name='name_river',
        ),
    ]
