# Generated by Django 3.2.6 on 2021-08-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20210824_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gidropost',
            old_name='river',
            new_name='name_river',
        ),
        migrations.RenameField(
            model_name='postreport',
            old_name='post',
            new_name='name_post',
        ),
        migrations.AlterUniqueTogether(
            name='postreport',
            unique_together={('name_post', 'report_time', 'report_type')},
        ),
    ]
