# Generated by Django 3.2.6 on 2021-08-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210825_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gidropost',
            old_name='name_post',
            new_name='post',
        ),
    ]
