# Generated by Django 3.2.6 on 2021-08-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_name_post_gidropost_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gidropost',
            old_name='post',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gidropost',
            name='geografic_koord',
        ),
        migrations.RemoveField(
            model_name='gidropost',
            name='height_BS',
        ),
        migrations.RemoveField(
            model_name='gidropost',
            name='istory_max_level',
        ),
        migrations.RemoveField(
            model_name='gidropost',
            name='pali_pruvodka',
        ),
        migrations.RemoveField(
            model_name='gidropost',
            name='reper',
        ),
        migrations.RemoveField(
            model_name='gidropost',
            name='reyka_max_pruvodka',
        ),
        migrations.RemoveField(
            model_name='gidropost',
            name='sposterigach',
        ),
        migrations.RemoveField(
            model_name='gidropost',
            name='telefon',
        ),
    ]
